" Start Vundle
source ~/.vim/vundle.vim
filetype plugin indent on

" set colorscheme
syntax enable
colorscheme molokai

set nu
set ruler
set cursorline
set colorcolumn=80

" Indent by filetype
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype markdown setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab

" search for ctags from current directory up to $HOME
set tags=./tags;$HOME

:set grepprg=grep\ -n\ -r\ --\ $*\ *\ /dev/null
