" Start Vundle
source ~/.vim/vundle.vim
filetype plugin indent on

" set colorscheme
syntax enable
colorscheme molokai

" turn on useful default plugins
runtime macros/matchit.vim


" better search
set ignorecase
set smartcase

set history=10000	" practically infinite history
set nu			" number line
set ruler		" column numbers
set laststatus=2
set cursorline		" highlight the current line
set colorcolumn=80
set backspace=2

" Turn off autocomment for css
autocmd Filetype css setlocal formatoptions-=cro

autocmd Filetype html setlocal ts=2 sw=2 expandtab noignorecase
autocmd Filetype markdown setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype python setlocal ts=4 sw=4 expandtab

autocmd Filetype racket let b:AutoPairs = {'(':')', '[':']', '{':'}', '"':'"', '`':'`'}

" Finding files
set path +=**

" Display all matching files when we tab complete
set wildmenu
set complete-=i

" search for ctags from current directory up to $HOME
set tags=./tags;$HOME

:set grepprg=grep\ -n\ -r\ --\ $*\ *\ /dev/null
